version: '2'

services:

  nginx:
    build: proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - ghost
    restart: always

  ghost:
    image: ghost:1-alpine
    volumes:
      - ./_ghost:/var/lib/ghost/content
    #ports:
    #  - "2368:2368"
    environment:
      NODE_ENV: production
      url: http://localhost/
    restart: always